app/urls.py
import importlib

from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # PERSONNAL VIEWS
    path('', include('apps.index.urls')),
    path('autocomplete/', include('apps.autocomplete.urls')),
    path('authenticate/', include('apps.login.urls')),
    path('account/', include('apps.account.urls')),
    path('products/', include('apps.products.urls')),
    # SOCIAL DJANGO
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

# try:
#     django_local = importlib.import_module("app.local_settings")
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
# except ImportError:
#     pass

apps/account/urls.py
"""account urls."""

from django.urls import path
from django.conf.urls import url

from . import views


urlpatterns = [
    path('', views.account, name='account'),
    path('remove_avatar', views.remove_avatar, name='remove_avatar'),
    path('profiles/<username>/', views.profiles, name='profiles'),
]

pure_beurre/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # PERSONNAL VIEWS
    path('', include('django_apps.index.urls')),
    path('autocomplete/', include('django_apps.autocomplete.urls'))
]

apps/account/models.py
from django.db import models

# Create your models here.

apps/account/forms.py
"""Account forms."""

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django import forms
from django.forms import ValidationError


class ProfileForm(forms.Form):
    """The account prfile form."""

    avatar = forms.FileField(
        help_text="Selectionnez une image.", required=False)

    description = forms.CharField(
        initial='Insérez une description...',
        required=False, widget=forms.Textarea)
    email = forms.EmailField(initial='', required=False, disabled=True)

    password = forms.CharField(widget=forms.PasswordInput, required=False)
    new_pass = forms.CharField(widget=forms.PasswordInput, required=False)
    confirm_new_pass = forms.CharField(
        widget=forms.PasswordInput, required=False)

    news_letter = forms.BooleanField(required=False)

    def clean_password(self):
        """Clean the password."""
        data = self.cleaned_data.get('password', "")
        if data:

            new = self.cleaned_data.get('new_pass', None)
            confirm = self.cleaned_data.get('confirm_new_pass', None)
            if new != confirm:
                raise ValidationError("Le nouveau mot de passe doit "
                                      "être identique dans les deux champs.")
        return data

    def change_password(self, user, request):
        """Check if password is set."""
        if user.social_auth.filter(provider='google-oauth2'):
            return

        password = self.cleaned_data.get('password', "")
        new_password = self.cleaned_data.get('new_pass', None)
        if not password and not new_password:
            return

        if not user.check_password(password):
            messages.error(request, 'mot de passe incorrect.')
            return

        if not new_password:
            messages.error(request, 'Veuillez entrer un nouveau mot de passe.')
            return

        user.set_password(new_password)
        user.save()
        update_session_auth_hash(request, user)
        messages.success(request, 'Mise à jour du mot de passe.')

    def change_avatar(self, user, request):
        """Check if avatar is set."""
        avatar = request.FILES.get("avatar")
        if not avatar:
            return

        else:
            user.profile.avatar.delete()
            user.profile.avatar = avatar
            user.save()
            messages.success(request, 'Avatar mis à jour.')

    def change_description(self, user, request):
        """Check if description is set."""
        description = self.cleaned_data.get('description', "")

        if description and description != user.profile.description:
            user.profile.description = description
            user.save()
            messages.success(request, 'Description mise à jour.')

    def change_news_letter(self, user, request):
        """Check if news_letter is set."""
        news_letter = self.cleaned_data.get('news_letter', "")

        if news_letter != user.profile.news_letter:
            user.profile.news_letter = news_letter
            if news_letter:
                user.email_user("Vous êtes désormais inscrits", "Merci !")
                messages.success(request, "Merci pour la souscription !")
            else:
                messages.success(request, "Vous êtes désinscrits. :(")
            user.save()

apps/account/views.py
"""Account views."""

from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from apps.login.models import Profile
from .forms import ProfileForm


@login_required()
def account(request):
    """Account view."""
    current_user = request.user
    initial = {'email': current_user.email,
               "news_letter": current_user.profile.news_letter,
               "username": current_user.username,
               'avatar': None,
               "description": current_user.profile.description}

    if request.method == 'POST':

        form = ProfileForm(request.POST, request.FILES, initial=initial)
        if form.has_changed() and form.is_valid():
            form.change_password(current_user, request)
            form.change_avatar(current_user, request)
            form.change_description(current_user, request)
            form.change_news_letter(current_user, request)

    else:
        form = ProfileForm(initial=initial)

    users = [user for user in Profile.objects.all()
             if current_user != user.user]
    return render(request, 'account.html', {"site_title": "Mon compte",
                                            "user": current_user,
                                            "users": users,
                                            "form": form})


@login_required()
def remove_avatar(request):
    """Remove_avatar view."""
    user = request.user
    user.profile.avatar.delete()
    user.save()
    messages.success(request, 'Avatar supprimé. Défaut: Gravatar.')
    return redirect("account")


def profiles(request, username=''):
    """Research a user."""
    other_user = User.objects.get(username=username)
    if other_user:
        return render(request, "profiles.html",
                      {"other_user": other_user,
                       "site_title": "Profiles"})
    else:
        return render(request, "no_profile_found.html",
                      {"site_title": "Aucun utilisateur"})

apps/account/templates/account.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% load webpack_static from webpack_loader %}
{% load static %}
{% load gravatar %}

<header class="text-white text-center account-header">
    <div class="background" style="background-image: url({% static 'account.jpg' %})"></div>
    <div class="container my-auto">
        <div class="row">
            <h1 class=""><strong>Mon compte - {{ user.get_username }}</strong></h1>
        </div>
    </div>
</header>
<div class="profile-div text-center">
    <hr>
    {% for message in messages %}

    <div class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}success{% endif %}">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}

    {% load widget_tweaks %}

    <form enctype="multipart/form-data" method="post" action="{% url 'account' %}" class="form-horizontal email-form">
        {% csrf_token %}


        <div class="form-group">

            <div class="label-div">
                <label class="control-label text-uppercase">Avatar :</label>
            </div>

            <div class="content-div avatar">
                {% if not user.profile.avatar %}
                {% gravatar user.email 150 "avatar" %}
                {% else %}
                <img class="gravatar" src="{{ user.profile.avatar.url }}" width="150" height="150" alt="avatar">
                {% endif %}
                <div class="add-file">
                    <label for="id_avatar">
                        <i class="material-icons-new twotone-add_photo_alternate" id="avatar-label"></i>
                    </label>
                    {% render_field form.avatar style="display: none;" %}
                    <a href="{% url 'remove_avatar' %}">
                        <i class="material-icons-new twotone-delete_forever" id="avatar-label"></i>
                    </a>
                </div>
                <p id="avatar-confirmation">
                </p>
            </div>

        </div>

        <div class="form-group">

            <div class="label-div">
                <label for="id_description" class="control-label text-uppercase">Description :</label>
            </div>

            <div class="content-div">
                {% render_field form.description class="form-control" %}
            </div>
        </div>

        <div class="form-group">

            <div class="label-div">
                <label for="email" class="control-label text-uppercase">Email :</label>
            </div>

            <div class="content-div">
                {% render_field form.email id="disabledInput" class="form-control" %}
            </div>

        </div>

        {% if not backends.associated %}
        <div class="form-group">

            <div class="label-div">
                <label class="control-label text-uppercase">Changer le mot de passe :</label>
            </div>
            <div class="content-div">
                <label for="ancien" class="control-label">Ancien mot de passe:</label>
                {% render_field form.password class="form-control" %}
                <label for="new" class="control-label">Nouveau mot de passe:</label>
                {% render_field form.new_pass class="form-control" %}
                <label for="confirm-new" class="control-label">Confirmer le nouveau mot de passe:</label>
                {% render_field form.confirm_new_pass class="form-control" %}
                <div class="pass-mess" id="pass-errors"></div>
            </div>
        </div>
        {% endif %}

        <div class="form-group">

            <div class="label-div">
                <label class="control-label text-uppercase">Recevoir les news-letter :</label>
            </div>

            <div class="content-div">
                {% render_field form.news_letter class="form-control" %}
            </div>

        </div>
        <div class="form-group">

            <div class="label-div">
                <!-- <label class="control-label text-uppercase">Recevoir les news-letter :</label> -->
            </div>

            <div class="content-div">
                <button class="btn" id="send-form" type="submit">mettre à jour des données</button>
            </div>

        </div>

        {{ form.username.as_hidden }}
    </form>



    {% if users %}
    <h3>Trouver d'autres utilisateurs :</h3>
    <div class="users">
        {% for a_user in users %}
        <div class="avatar">
            <a href="{% url 'profiles' username=a_user.user.username %}">
                <h4>{{ a_user.user.username }}</h4>
                {% if not a_user.avatar %}
                {% gravatar a_user.user.email 150 "avatar" %}
                {% else %}
                <img class="gravatar" src="{{ a_user.avatar.url }}" width="150" height="150" alt="avatar">
                {% endif %}
            </a>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

apps/account/templates/profiles.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% load webpack_static from webpack_loader %}
{% load static %}
{% load gravatar %}

<header class="text-white text-center account-header">
    <div class="background" style="background-image: url({% static 'account.jpg' %})"></div>
    <div class="container my-auto">
        <div class="row">
            <h1 class=""><strong>Compte de {{ other_user.username }}</strong></h1>
        </div>
    </div>
</header>
<div class="profile-div text-center">
    <hr>

    {% load widget_tweaks %}



    <div class="content-div avatar">
        {% if not other_user.profile.avatar %}
        {% gravatar other_user.email 150 "avatar" %}
        {% else %}
        <img class="gravatar" src="{{ other_user.profile.avatar.url }}" width="150" height="150" alt="avatar">
        {% endif %}
    </div>

    <div class="profile-description">
        {{ other_user.profile.description }}
    </div>


    {{ form.username.as_hidden }}
</div>
{% endblock %}